version: '3.8'

services:
  db:
    image: postgres:17
    container_name: userfa_postgres
    environment:
      POSTGRES_DB: userfa
      POSTGRES_USER: userfa_user
      POSTGRES_PASSWORD: userfa_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: userfa_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userfa
      SPRING_DATASOURCE_USERNAME: userfa_user
      SPRING_DATASOURCE_PASSWORD: userfa_pass
    restart: always

volumes:
  postgres_data:
